dataset_name: thumos
train_split: ['validation']
val_split: ['test']
dataset: {
  json_file: /mnt/DataDrive164/zhanghao/datasets/thumos14_lite/actionformer_thumos/annotations/thumos14.json,
  feat_folder: /mnt/DataDrive164/yjh/i3d_features,
  clip_image_folder: /mnt/DataDrive164/caoqiushi/thumos14/features_clip2_duiqi,
  clip_text_folder: /mnt/DataDrive164/caoqiushi/thumos14/text（action）,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 20,
  input_dim: 512,
  feat_stride: 4,
  num_frames: 16,
  # serve as data augmentation
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,  #原本是2304，由于层数扩大到10层所以需要增大这个值18432
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 19,
}
opt: {
  learning_rate: 0.0003,
  epochs: 50,
  weight_decay: 0.025,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
test_cfg: {
  voting_thresh: 0.07,
  pre_nms_topk: 2000,
  max_seg_num: 2000,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: ./ckpt/
